spring:
  database:
    url: jdbc:mysql://localhost:3306/product
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sudha@9951
  jpa:
    hibernate:
      ddl-auto: update
    
